# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml


# 追加した規約ファイル読込
require:
  - rubocop-rails
  - rubocop-performance

AllCops:
    # Rubyバージョン指定
    TargetRubyVersion: 2.6.3

    # 除外
    Exclude:
      - 'Gemfile'
      - 'config.ru'
      - 'bin/**'
      - 'lib/**'
      - 'db/**/*'
      - 'config/**/*'
      - 'test/**/*'
      - 'spec/**/*'
      - 'script/**/*'
      - !ruby/regexp /old_and_unused\.rb$/
      - 'node_modules/**/*'
      - "public/**/*"
      - "log/**/*"
      - "tmp/**/*"
      - "vendor/**/*"

  # 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

#文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメントのないclassを許可する
Style/Documentation:
  Enabled: false

# 1行の最大文字数を150字にする
LineLength:
  Max: 150

#代入少なく、関数呼び出し少なく、制御構文少なく 
Metrics/AbcSize:
  Max: 40

#追記2020/9/7
# For rubocop < 1.0.0
Style/HashEachMethods:
  Enabled: false

# For rubocop < 1.0.0
Style/HashTransformKeys:
  Enabled: false

# For rubocop < 1.0.0
Style/HashTransformValues:
  Enabled: false

MethodLength:
  CountComments: true
  Max: 40