version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/foods_app
      - public-data:/foods_app/public
      - tmp-data:/foods_app/tmp
      - log-data:/foods_app/log
    
  web:
    build:
      context: ./nginx
    volumes:
      - public-data:/foods_app/public
      - tmp-data:/foods_app/tmp
    ports:
      - 80:80

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:

